id = "68fec58e-b8bf-4c9e-b2ed-34155a19d960"
worktree_path = "/Users/akio-jinsenji/Workbench/llmlb/.worktrees/feature-llmlb"
branch = "feature/llmlb"
created_at = "2026-01-23T06:45:14.967904Z"
updated_at = "2026-01-24T06:09:45.783596Z"
status = "running"
last_activity_at = "2026-01-24T06:09:45.783596Z"
